pull_request_rules:
  - name: merge into development
    conditions:
      - status-success=ci/bitrise/a3630b2c59177ea1/pr
      - base=development
    actions:
      merge:
        method: merge
      delete_head_branch: {}
  - name: close PR into development on CI failure
    conditions:
      - status-failure=ci/bitrise/a3630b2c59177ea1/pr
      - base=development
    actions:
      close: {}
  - name: merge into master
    conditions:
      - status-success=ci/bitrise/a3630b2c59177ea1/pr
      - base=master
    actions:
      merge:
        method: merge
  - name: close PR into master on CI failure
    conditions:
      - status-failure=ci/bitrise/a3630b2c59177ea1/pr
      - base=master
    actions:
      close: {}
